### ISSUE TITLE
org.webjars.play.RequireJS.setup pulls in wrong dependency of jquery-ui

### ISSUE THREAD

**Issue by almoehi** [webjars/jquery-ui-touch-punch#6]
this webjar pulls in the jquery-ui dependency - however, the generated requireJS code by `@Html(org.webjars.play.RequireJS.setup("javascripts/main"))` pulls in jquery-ui-min instead:

```
requirejs.config({"paths":{"jquery-ui-min":["/webjars/jquery-ui/1.10.4/ui/minified/jquery-ui.min","ui/minified/jquery-ui.min"]},"shim":{"jquery-ui-min":["jquery"]}})
requirejs.config({"paths":{"jquery-ui-touch-punch":["/webjars/jquery-ui-touch-punch/0.2.3/jquery.ui.touch-punch","jquery.ui.touch-punch"]},"shim":{"jquery-ui-touch-punch":["jquery-ui"]}})
```

which results in a jrequireJS error like:

```
"NetworkError: 404 Not Found - http://localhost:7070/assets/javascripts/jquery-ui.js"
```

it looks like the setup code automatically figures out if a webjar provides a "*-min" version and pulls it in in favour of the plain version.
So, should we change this jquery-ui dep here to jquery-ui-min OR change the setup code generator ?

**Comment by jamesward** [comment]
Can you try to explicitly set a dependency on the newest version of `jquery-ui`?  That one has a module defined as `jquery-ui` (non-min).

**Comment by almoehi** [comment]
adding jquery-ui webjar as dep to my build.sbt worked :+1: 
so, will I have to add all deps my webjars depend on manually to my build.sbt? Or is it just sbt-web pulling in the wrong jquery-ui version?
I thought resolving these deps automatically is the purpose of sbt-web? :-)

**Comment by jamesward** [comment]
The transitive dependency defined in this WebJar depends on an older version of `jquery-ui`.  Setting the dependency explicitly overrides the default. We should bump the dependency in this project so that others don't have this same issue.

**Comment by almoehi** [comment]
ok, I see - sent a PR.
I'm probably sending a few more as I'm going to use quite a few webjars and will update the POMs when I run into issues.
